# version: "3"

services:
  fb-api:
    hostname: fb-api
    build:
      context: ./services/fb
      dockerfile: Dockerfile
    env_file:
      - ./infra/envs/prod/.env.prod.fb_api
    volumes:
      - ./services/fb/src:/fortuna/src
    networks:
      - proxy-net
      - mongo-db-net
    ports:
      - 5002:5002
    depends_on:
      - mongo_db
