# Generated by Django 3.2.22 on 2023-11-14 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("address", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name="DepartmentInfo",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "owner_type",
                    models.CharField(
                        choices=[
                            ("GV", "Governmental"),
                            ("QGV", "Quazi-Governmental"),
                            ("PV", "Private"),
                        ],
                        default="GV",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(max_length=400)),
                ("owner_id", models.CharField(max_length=200)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "activity_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="department.activity",
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="address.address",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=400)),
                ("owner_id", models.CharField(max_length=200)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "department_info_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="department.departmentinfo",
                    ),
                ),
                (
                    "parent_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="department.department",
                    ),
                ),
            ],
        ),
    ]
