# Generated by Django 3.2.22 on 2023-11-14 17:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("department", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"verbose_name_plural": "Деятельность подразделения"},
        ),
        migrations.AlterModelOptions(
            name="department",
            options={"verbose_name_plural": "Подразделение"},
        ),
        migrations.AlterModelOptions(
            name="departmentinfo",
            options={"verbose_name_plural": "Информация о подразделении"},
        ),
    ]
