# Generated by Django 3.2.22 on 2023-11-16 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0002_auto_20231114_2055"),
        ("department", "0002_auto_20231114_2054"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="department_info_id",
        ),
        migrations.AddField(
            model_name="department",
            name="activity_id",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="department.activity",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="department",
            name="address",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="address.address",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="department",
            name="owner_type",
            field=models.CharField(
                choices=[
                    ("GV", "Государственный"),
                    ("QGV", "Квазигосударственный"),
                    ("PV", "Частный"),
                ],
                default="GV",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="DepartmentInfo",
        ),
    ]
