# Generated by Django 3.2.22 on 2023-11-16 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("department", "0003_auto_20231116_1505"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="description",
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name="department",
            name="description",
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=25)),
                ("description", models.TextField(blank=True, max_length=200)),
                ("owner_id", models.CharField(max_length=200)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "department_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="department.department",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Должность",
            },
        ),
    ]
