# Generated by Django 3.2.22 on 2023-11-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("department", "0006_alter_department_owner_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="owner_type",
            field=models.CharField(
                choices=[
                    ("GV", "Государственный"),
                    ("QGV", "Квазигосударственный"),
                    ("PV", "Частный"),
                ],
                default="GV",
                max_length=20,
            ),
        ),
    ]
