# Generated by Django 3.2.22 on 2024-02-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("department", "0008_alter_department_owner_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(max_length=40),
        ),
    ]
