# Generated by Django 3.2.22 on 2023-11-14 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("address", "0001_initial"),
        ("department", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("surname", models.CharField(max_length=25)),
                ("name", models.CharField(max_length=25)),
                ("lastname", models.CharField(max_length=25)),
                ("birthday", models.DateField()),
                ("biography", models.TextField(max_length=1000)),
                ("owner_id", models.CharField(max_length=200)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees_location",
                        to="address.address",
                    ),
                ),
                (
                    "place_of_birth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees_birthplace",
                        to="address.address",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=25)),
                ("description", models.TextField(max_length=200)),
                ("date_start", models.DateField()),
                ("date_end", models.DateField(null=True)),
                ("owner_id", models.CharField(max_length=200)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "department_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="department.department",
                    ),
                ),
                (
                    "employee_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee.employee",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="employee",
            name="positions",
            field=models.ManyToManyField(
                through="employee.Position", to="department.Department"
            ),
        ),
    ]
