# Generated by Django 3.2.22 on 2023-11-14 17:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"verbose_name_plural": "Сотрудник"},
        ),
        migrations.AlterModelOptions(
            name="position",
            options={"verbose_name_plural": "Должность"},
        ),
    ]
