# Generated by Django 3.2.22 on 2023-11-16 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("department", "0004_auto_20231116_1847"),
        ("employee", "0002_auto_20231114_2055"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeePosition",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="employee",
            name="positions",
        ),
        migrations.AlterField(
            model_name="employee",
            name="biography",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.DeleteModel(
            name="Position",
        ),
        migrations.AddField(
            model_name="employeeposition",
            name="employee_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="employee.employee"
            ),
        ),
        migrations.AddField(
            model_name="employeeposition",
            name="position_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="department.position"
            ),
        ),
    ]
