# Generated by Django 3.2.22 on 2023-11-16 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0003_alter_address_postal_code"),
        ("employee", "0003_auto_20231116_1847"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employeeposition",
            options={"verbose_name_plural": "Сотрудник-Должность"},
        ),
        migrations.AlterField(
            model_name="employee",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="lastname",
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name="employee",
            name="location",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees_location",
                to="address.address",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name="employee",
            name="place_of_birth",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees_birthplace",
                to="address.address",
            ),
        ),
    ]
