# Generated by Django 3.2.22 on 2023-11-16 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0003_alter_address_postal_code"),
        ("employee", "0004_auto_20231116_1905"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees_location",
                to="address.address",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="place_of_birth",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees_birthplace",
                to="address.address",
            ),
        ),
    ]
