# Generated by Django 3.2.22 on 2023-11-16 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0005_auto_20231116_1906"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeposition",
            name="created_at",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employeeposition",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employeeposition",
            name="owner_id",
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
