# Generated by Django 3.2.22 on 2023-11-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0006_auto_20231116_1953"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeposition",
            name="finish_date",
            field=models.DateField(blank=True, default="1970-01-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employeeposition",
            name="start_date",
            field=models.DateField(blank=True, default="1970-01-01"),
            preserve_default=False,
        ),
    ]
