# Generated by Django 3.2.22 on 2023-11-17 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0008_auto_20231117_2223"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeeposition",
            name="finish_date",
        ),
        migrations.RemoveField(
            model_name="employeeposition",
            name="start_date",
        ),
    ]
