# Generated by Django 3.2.22 on 2023-11-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0011_auto_20231117_2237"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeposition",
            name="finish_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employeeposition",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
