# Generated by Django 3.2.22 on 2023-11-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0002_auto_20231114_2055"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
