# Generated by Django 3.2.22 on 2023-11-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0003_alter_address_postal_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
