# Generated by Django 3.2.22 on 2024-02-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0004_auto_20231116_1953"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="postal_code",
        ),
        migrations.AddField(
            model_name="address",
            name="description",
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
