version: "3.7"

networks:
  gelios-dev-net:

include:
  - path:
      - ./docker-compose.root.yml
      - ./web/docker-compose.dev.yml
      - ./backend/docker-compose.dev.yml
      - ../../services/admin-api/docker-compose.dev.yml

services:
  gelios-oauth-proxy:
    container_name: gelios-oauth-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
    command: --config /oauth2-proxy.cfg
    hostname: gelios-oauth-proxy
    volumes:
      - "./configs/oauth2-proxy-keycloak.dev.cfg:/oauth2-proxy.cfg"
    restart: unless-stopped
    networks:
      gelios-dev-net:
    depends_on:
      - gelios-web
      - gelios-api
    ports:
      - 3001:4180
  