import enum


class ServerState(enum.Enum):
    PENDING_FIRST_STARTUP = "PENDING_FIRST_STARTUP"
    PENDING_LOAD_CHAIN = "PENDING_LOAD_CHAIN"
    ARCHIVED = "ARCHIVED"
    READY = "READY"
    BUSY = "BUSY"
    UNAVAILABLE = "UNAVAILABLE"
