import enum


class ChainState(enum.Enum):
    PENDING_FIRST_STARTUP = "PENDING_FIRST_STARTUP"
    READY = "READY"
    PENDING_ARCHIVED = "PENDING_ARCHIVED"
    ARCHIVED = "ARCHIVED"
    CREATE_CLIENT = "CREATE_CLIENT"
    REVOKE_CLIENT = "REVOKE_CLIENT"
