from enum import Enum


class Errors(Enum):
    SERVER_IS_NOT_EXIST = "SERVER_IS_NOT_EXIST"
    SERVER_IS_NOT_AVAILABLE_FOR_MODIFICATION = (
        "SERVER_IS_NOT_AVAILABLE_FOR_MODIFICATION"
    )
    SERVER_IS_NOT_AVAILABLE_FOR_WORKING = "SERVER_IS_NOT_AVAILABLE_FOR_WORKING"

    USER_IS_NOT_EXIST = "USER_IS_NOT_EXIST"
    PERMISSION_DENIED = "PERMISSION_DENIED"

    CHAIN_IS_NOT_EXIST = "CHAIN_IS_NOT_EXIST"
    CHAIN_IS_NOT_AVAILABLE = "CHAIN_IS_NOT_AVAILABLE"

    WRONG_CHOICE_OF_SERVERS = "WRONG_CHOICE_OF_SERVERS"
    CHAIN_CLIENT_IS_NOT_EXIST = "CHAIN_CLIENT_IS_NOT_EXIST"
